# Generated by Django 2.1.7 on 2019-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogger_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='My content goes here', help_text='Write your post here', max_length=10000),
            preserve_default=False,
        ),
    ]
